---
title: "Regression Tables"
author: "Zhaochen He"
date: sysdate
output: html_document
---

<style>
table, td, th {
  border: none;
  padding-left: 1em;
  padding-right: 1em;
  min-width: 50%;
  margin-left: auto;
  margin-right: auto;
  margin-top: 1em;
  margin-bottom: 1em;
}
</style>


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

```

## Section 1
```{r sec1, results = 'asis'}
regdir = getReg(1.1,regdir.good)

#t = getReg
xlabels = regdir$xlab


column.labels = c('OLS','Probit','Logit','Probit (No FE)','Probit (No Weights)','Probit (Horse-race)')
column.separate = c(2,2,2,2,2,2)
dep.var.labels = rep(c('Trump G.E.',' Trump Prim.'),6)

stargazer(c(modcces),
          type = 'html', 
          title = 'Regressions', 
          report = 'vc*sp', 
          covariate.labels = xlabels,
          column.labels = column.labels,
          column.separate = column.separate,
          dep.var.labels = dep.var.labels,
          model.names=F,
          model.numbers=F,
          omit = c('stateabr')
          )

```

## Section 2
```{r results = 'asis'}
regdir = getReg(2.1,regdir.good)
xlabels = regdir$xlab
mod = modcnty$ols

column.labels = c('Unscaled','Feature-Scaled')
column.separate = c(7,7)
dep.var.labels = rep(c('Trump G.E.',' Trump Prim.'),6)



stargazer(c(modcnty),
          type = 'html', 
          title = 'Regressions', 
          report = 'vc*sp',
          covariate.labels = xlabels,
          column.labels = column.labels,
          column.separate = column.separate,
          #dep.var.labels = dep.var.labels,
          #model.names=F,
          #model.numbers=F,
          omit = c('stateabr')
          )

```
