---
title: "Exploring CCES Data"
author: "Zhaochen He"
date: "July 21, 2018"
output: html_document
---

```{r prep, include=FALSE}
# Get list of variables from John's CCES data, export to CSV, then paste into gsheets
setproj(10)
loadmain()
require(googlesheets)
gs_ls()  # Upon first login, need to authenticate
knitr::opts_chunk$set(echo = TRUE)
```

```{r getvars, include=FALSE}
varguide = data.table(vname = names(ccesplus))
cces.meta$vname = paste('cc.',cces.meta$vname,sep='')
varguide = merge(varguide,cces.meta[1:3],all.x=T,sort=F,by='vname')
gsKey = '1F9WgoFMqd0yHVtc7ux1mAtntdOhAx6igw9ylo-PGxGs'
gstarget = gs_key(gsKey)
gs_edit_cells(ss = gstarget, ws = 'ccesplus raw', input = varguide,trim =F,verbose=F) #takes awhile
# fwrite(varguide,paste0(datpath,'ccesvarlist.csv'))







```

```{r corrtable, include=FALSE}
# Get Correlations
# First, get varnames from ccesplus guide, then filter for nonempty flag1, this is the longlist of variables

gsdat = data.table(gs_read(gs_key(gsKey),ws='ccesplus guide'))
datvars = gsdat[!is.na(flag1),vname]


corguide = data.frame(vname = datvars, cortrump.p = '',cortrump.ge = '',stringsAsFactors = F)
for (i in 1:length(datvars)) {
   
   x = select(ccesplus,datvars[i])
   corguide[i,'cortrump.p'] = 
      as.character(try(round(cor(x,ccesplus$cc.TrumpPVote,use='pairwise'),3),silent=T))
   corguide[i,'cortrump.ge'] =
      as.character(try(round(cor(x,ccesplus$cc.TrumpGEVote,use='pairwise'),3),silent=T))
   corguide[i,'numobs'] = round(nrow(x[!is.na(get(datvars[i])),]),2)
   corguide[i,'pctobs'] = round(nrow(x[!is.na(get(datvars[i])),])/nrow(x),2)
}

# Write to Google Sheets and csv
to.gs = merge(varguide,corguide,all.x=T,sort=F)
#fwrite(to.gs,paste0(datpath,'cces_corr.csv'))
gstarget = gs_key(gsKey)
#try(gs_ws_delete(ss = gstarget, ws = 'fromR'))
gs_edit_cells(ss = gstarget, ws = 'corr from R', input = to.gs,trim =F,verbose=F)
```

